### ISSUE TITLE
No crowdhuman_dataset

### ISSUE THREAD

**Issue by szh91** [PeizeSun/TransTrack#1]
hi, can you give the crowdhuman dataset link?

**Comment by PeizeSun** [comment]
Hi~
We just update the readme and add dataset link.

The official website of CrowdHuman provides dataset [link](https://www.crowdhuman.org/)
Its original annotation format is odgt, we provide [json format]( https://drive.google.com/drive/folders/1DjPL8xWoXDASrxgsA3O06EspJRdUXFQ-?usp=sharing).

**Comment by szh91** [comment]
thank you.  I find seven files (CrowdHuman_train 01~03,CrowdHuman_val, annotation_train.odgt ,annotation_val.odgt  and CrowdHuman_test). I need to download all files?

**Comment by iFighting** [comment]
> thank you. I find seven files (CrowdHuman_train 01~03,CrowdHuman_val, annotation_train.odgt ,annotation_val.odgt and CrowdHuman_test). I need to download all files?

yes, you need to download all files

**Comment by Yinyf0804** [comment]
Hi,
After downloading all files (CrowdHuman_train 01~03,CrowdHuman_val, annotation_train.odgt ,annotation_val.odgt and CrowdHuman_test), what kind of structure should I prepare the data in?

**Comment by PeizeSun** [comment]
> Hi, After downloading all files (CrowdHuman_train 01~03,CrowdHuman_val, annotation_train.odgt ,annotation_val.odgt and CrowdHuman_test), what kind of structure should I prepare the data in?

The structure of the dataset is as README -- Installation -- 2. Prepare datasets and annotations .

**Comment by gyh420** [comment]
when l python tools/convert_crowdhuman_to_coco.py   l have this  No such file or directory: 'datasets/crowdhuman/CrowdHuman_val/273271,c9db000d5   how to do it

**Comment by gyh420** [comment]
> Hi~ We just update the readme and add dataset link.
> 
> The official website of CrowdHuman provides dataset [link](https://www.crowdhuman.org/) Its original annotation format is odgt, we provide [json format](https://drive.google.com/drive/folders/1DjPL8xWoXDASrxgsA3O06EspJRdUXFQ-?usp=sharing).

can you give me the json format in other way? l can not open google

**Comment by jer1ry** [comment]
@gyh420 
Hi~
Did you solve this problem? And successfully reproduced the code of the paper, I would like to know the method, thank you very much

**Comment by gyh420** [comment]
> 

do not do it in zip
