### ISSUE TITLE
Question about demo

### ISSUE THREAD

**Issue by raja1196** [PeizeSun/TransTrack#10]
Thanks for releasing the code implementation of TransTrack. 
I noticed that you have mentioned in the requirements about demo. Is there a timeline to release demo files so that we can test the pre-trained models on our own videos?

**Comment by PeizeSun** [comment]
Hi~
Please refer to step6 in README.

**Comment by raja1196** [comment]
Hello, I went through the txt2video.py under the track_tools for the demo. It looks like they are only for MOT train/val videos. Is it possible to test on our own videos?

**Comment by PeizeSun** [comment]
> Hello, I went through the txt2video.py under the track_tools for the demo. It looks like they are only for MOT train/val videos. Is it possible to test on our own videos?

Yep~
1. Convert your own videos annotations as the [format](https://github.com/PeizeSun/TransTrack/blob/main/track_tools/convert_mot_to_coco.py) 
2. Run the evaluation code
3. Change txt2video.py and run it
