### ISSUE TITLE
Train on custom dataset

### ISSUE THREAD

**Issue by raja1196** [PeizeSun/TransTrack#11]
How can we train the algorithm on a custom dataset? Is there a generate_labels files or any steps to prepare the data for training purposes?

**Comment by PeizeSun** [comment]
Hi~
In order to train on a custom dataset, you need to prepare the annotations as coco format, for example, 
[convert_mot_to_coco](https://github.com/PeizeSun/TransTrack/blob/main/track_tools/convert_mot_to_coco.py)
