### ISSUE TITLE
The different of tracktrainall.py, tracktrainhalf.py and main.py

### ISSUE THREAD

**Issue by RuohanZhang** [PeizeSun/TransTrack#13]
Hi~ I noticed that the training files in the code include tracktrainall.py, tracktrainhalf.py and main.py. Their codes are very similar. Is the difference only in the training data? Hope I did not miss important informations.
thank you

**Comment by PeizeSun** [comment]
Hi~
I am sorry for not arranging code elegantly. 
Their differences are only in the training data.

We will re-arrange the code later.

**Comment by PeizeSun** [comment]
Hi, we have re-arranged the code!
