### ISSUE TITLE
 About training

### ISSUE THREAD

**Issue by lichunxiang93** [PeizeSun/TransTrack#14]
thank you for your sharing，I have a few questions，Hope you can answer。
1、 I noticed that you have given the results of training using only the crowdHuman data set. I would like to ask whether this algorithm can achieve the purpose of tracking only by using the pedestrian detection data set training?
2、Can I use a large number of target detection data sets combined with a small number of tracking data sets for training？

**Comment by PeizeSun** [comment]
Hi~
1. Of course. Please see "Evaluate pre-trained CrowdHuman model on MOT" in readme.
2. In fact, our code is only based on detection data to train a tracking model. The key is (1) random select an image (2) its adjacent frame image is simulated by randomly scaling and translating this image.
