### ISSUE TITLE
Implementation details: Current Dataloader and Dataset class supports only static images.

### ISSUE THREAD

**Issue by sramakrishnan247** [PeizeSun/TransTrack#16]
Firstly, thanks for sharing the code!
Quoting from the paper:
Training Data. The training data of TransTrack could be the same as most other tracking methods, in which two consecutive frames or two randomly selected frames from a short sequence are used as training samples. **_Furthermore, training data could also be the static image [45], where the adjacent frame is simulated by randomly scaling and trans- lating the static image._**

I believe the highlighted method is how the data is being loaded. 
Is there any advice/support on how to load the current frame and previous frame?

It would also be really helpful if you share some references if you do not have support for this method.
Also, did picking the consecutive frame affect the results in anyway. 

Thanks in advance.

**Comment by PeizeSun** [comment]
Hi~
We will support loading the current frame and previous frame in recent weeks.

**Comment by sramakrishnan247** [comment]
Got it, thanks!

**Comment by ziqi123** [comment]
> 
 Hello,thanks for sharing the code!Do you support loading the current frame and previous frame now?
