### ISSUE TITLE
KeyError: 'age'

### ISSUE THREAD

**Issue by davidyang180** [PeizeSun/TransTrack#18]
What caused the following problem during the test,Thanks!
Traceback (most recent call last):
  File "main_track.py", line 369, in <module>
    main(args)
  File "main_track.py", line 292, in main
    phase='eval', det_val=args.det_val)
  File "/data1/anaconda3/envs/TransTrack/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/data1/PycharmProjects/TransTrack/engine_track.py", line 156, in evaluate
    res_track = tracker.step(results[0])
  File "/data1/PycharmProjects/TransTrack/models/tracker.py", line 123, in step
    if track['age'] < self.max_age:

**Comment by PeizeSun** [comment]
Hi~
Which model do you use?  And I guess you change some codes in  main_track.py and engine_track.py(the line number doesn't match the original code), is this the possible reason?

**Comment by davidyang180** [comment]
Hi~Thank you very much for your reply!
I just tried to train on the mot15val dataset, and then this error occurred when I tested on the validation set.

**Comment by PeizeSun** [comment]
which part of codes is changed?

**Comment by davidyang180** [comment]
Basically no code changes. After importing mot15 dataset, the label is obtained by ‘convert_mot_to_coco.py‘ ,and then the data path is directly changed for training in main_track.py.
After that, I used the original code to train in mot15 to see if it was caused by my unintentional changes.

**Comment by PeizeSun** [comment]
How about MOT17?  Can you reproduce our reported results without bugs?

**Comment by davidyang180** [comment]
Yes!no error; I've run mot17 and mot16 successfully before, but I'm trained with 'main_tracktrainhalf.py'. And I downloaded the last version of this code last month, and then I saw you update the new version of the code. After I changed it, using 'main_track.py' training, it seems that there is a bit of error.
I'll compare it with the original code training later. If there is any problem, I'll report it again.Thanks!

**Comment by PeizeSun** [comment]
Great ! Thank you~

**Comment by davidyang180** [comment]
Hello! After testing,the original code can be trained on mot15, 16, 17, 20 datasets. But it's puzzling why the result of mot15 dataset is so bad, especially in KITTI dataset with some shadows, and even eth Bahnhof dataset which should achieve better results, it doesn't get the expected results.

**Comment by davidyang180** [comment]
![QQ截图20210421182454](https://user-images.githubusercontent.com/45596935/115539204-4422e680-a2cf-11eb-8089-a1c33410d327.jpg)

**Comment by PeizeSun** [comment]
How about adjusting the score threshold to see whether  KITTI and Bahnhof dataset could be improved?
Btw, do you find the error in main_track.py, comparing with main_tracktrainhalf.py?

**Comment by davidyang180** [comment]
Hello! After testing the main.py and the main_track.py, i find that there are some bugs in the evaluate function in the engine_track.py, while the evaluate function in the main.py can be tested successfully, but the evaluate function of the main_track.py can not run, and this problem only exists on the mot15 dataset.It can be successfully verified in mot16, mot17 and mot20 datasets.But I haven't found out where the code went wrong yet.
Btw, I can only achieve such a better result by adjusting the score threshold, but as you can see from the output,it still gets an unsatisfactory result on the KITTI dataset.It seems to miss the target by mistake and recognize it again on the KITTI 17.

**Comment by davidyang180** [comment]
![MOT15 MOTA](https://user-images.githubusercontent.com/45596935/115713350-7c4a2800-a3a8-11eb-9dea-bc908cafcb82.jpg)

**Comment by PeizeSun** [comment]
> What caused the following problem during the test,Thanks!
> Traceback (most recent call last):
> File "main_track.py", line 369, in
> main(args)
> File "main_track.py", line 292, in main
> phase='eval', det_val=args.det_val)
> File "/data1/anaconda3/envs/TransTrack/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
> return func(*args, **kwargs)
> File "/data1/PycharmProjects/TransTrack/engine_track.py", line 156, in evaluate
> res_track = tracker.step(results[0])
> File "/data1/PycharmProjects/TransTrack/models/tracker.py", line 123, in step
> if track['age'] < self.max_age:

Hi~
We just fix this bug in [issue25](https://github.com/PeizeSun/TransTrack/issues/25). Can you test on your dataset to see whether it works? Thx~
