### ISSUE TITLE
error in ms_deformable_col2im_cuda: invalid device function

### ISSUE THREAD

**Issue by ssyou** [PeizeSun/TransTrack#2]
Help, help! Thanks

**Comment by PeizeSun** [comment]
Can you provide more details?

**Comment by GehenHe** [comment]
Same issue. I met this error when run 'python test.py' in ''models/ops'' directory, after  I build & install related packages by 'python setup.py build install'

Any suggest about this issue?

**Comment by GehenHe** [comment]
The environment is :
```
python=3.7
gcc = 5.4
pytorch=1.5.1
torchvision=0.6
cuda=10.1
```

**Comment by GehenHe** [comment]
I found that install pytorch=1.5.1 with cuda 9.2 will solve this issue：

```conda install pytorch=1.5.1 torchvision=0.6.1 cudatoolkit=9.2 -c pytorch```

It seems that the cuda operator does not support cuda 10+
