### ISSUE TITLE
Pre-training both detection and tracking

### ISSUE THREAD

**Issue by lihanlin99** [PeizeSun/TransTrack#20]
Hi~ Thanks for your code and updating! I have a questioin:
Now, is it pre-training both detection and tracking by running  track_exps/crowdhuman_train.sh ?

**Comment by PeizeSun** [comment]
Yep~ We also provide the pre-trained model [crowdhuman_final.pth](https://drive.google.com/drive/folders/1DjPL8xWoXDASrxgsA3O06EspJRdUXFQ-?usp=sharing)

**Comment by Xingyu-Jin** [comment]
good question and i'm a bit lost on what u mean by pretraining both detection and tracking. 

the crowdhuman is detection dataset consisting of images rather than videos, i.e. there is no association between images in this dataset. How is it used to train on tracking ?

Many thanks

**Comment by PeizeSun** [comment]
> good question and i'm a bit lost on what u mean by pretraining both detection and tracking.
> 
> the crowdhuman is detection dataset consisting of images rather than videos, i.e. there is no association between images in this dataset. How is it used to train on tracking ?
> 
> Many thanks

Hi~ When training on static images, adjacent frame is simulated by randomly scaling and translating the static image.

**Comment by Xingyu-Jin** [comment]
Brilliant. Good way to make use of more dataset!
