### ISSUE TITLE
Release the model fine-tuned on mixed data

### ISSUE THREAD

**Issue by Xingyu-Jin** [PeizeSun/TransTrack#21]
Hi thanks for the amazing work and the updates. 

In the latest update, you mentioned mixture of both dataset gives better perforamnce and the command of preprocessing and training is listed in https://github.com/PeizeSun/TransTrack#test-set

but I didn't see the model uploaded. DId i miss smth or would you like to share that model?

**Comment by PeizeSun** [comment]
Hi~
We won't release trained models for test test. Running as in [Steps](https://github.com/PeizeSun/TransTrack/blob/main/README.md#steps-1)  could reproduce them.
