### ISSUE TITLE
Is that supported to convent to onnx 

### ISSUE THREAD

**Issue by sYANGunique1111** [PeizeSun/TransTrack#22]
I was trying to connevt the Transtrack model to onnx, It seemed it didn't work well. 
First time I tired to do it on gpu, but onnx returns me an error
![Screenshot from 2021-05-10 14-39-21](https://user-images.githubusercontent.com/74031170/117660880-f991dd00-b19d-11eb-8697-f39d51387838.png)

But after I change them to cpu,  MSDeformAttnFunction returns me another error. 
![Screenshot from 2021-05-10 14-40-03](https://user-images.githubusercontent.com/74031170/117661245-65744580-b19e-11eb-9d02-1b4b96a49ee4.png)

Therefore is that possible to convert the transtrack model to onnx

**Comment by PeizeSun** [comment]
Hi~ 
We don't support to convert to onnx.

**Comment by Xingyu-Jin** [comment]
Hi @sYANGunique1111 ,  have you magaged to get onnx conversion?

**Comment by sYANGunique1111** [comment]
@Xingyu-Jin  No, I eventually gave it up. It seemed like some version issue for me

**Comment by HaithemH** [comment]
@PeizeSun did you or willing to realease the onnx conversion script ?
