### ISSUE TITLE
Hello! I have some questions about the model

### ISSUE THREAD

**Issue by davidyang180** [PeizeSun/TransTrack#23]
In this paper, it is mentioned that the encoder combines the feature map extracted by the backbone from the current frame with the feature map preserved in the previous frame as the input;
But in the implementation of the paper, I found that it seems not to do this operation, but to concat the feature of the two same current frame pictures.
![image](https://user-images.githubusercontent.com/45596935/117947142-7cec3380-b342-11eb-86bf-fb8396776132.png)

**Comment by davidyang180** [comment]
Moreover, the features of the previous frame used in the training process are not the real previous frame, but are obtained by training after the current image interpolation.
Will such operation affect the following tracking results?Thanks!
![image](https://user-images.githubusercontent.com/45596935/117946093-8c1eb180-b341-11eb-9d44-2649fbb58f42.png)

**Comment by PeizeSun** [comment]
Hi~
We update the code recently. The code you show is the deprecated version.

**Comment by davidyang180** [comment]
Hello! Thank you for your answer. I looked at the latest code and found that the features of the previous frame used in the training process were obtained through training after the current image interpolation.
Under the premise of the same amount of training computation, using the previous frame ID to find the real previous frame image and target information as cancat features, will the effect be better?

**Comment by PeizeSun** [comment]
> Hello! Thank you for your answer. I looked at the latest code and found that the features of the previous frame used in the training process were obtained through training after the current image interpolation. Under the premise of the same amount of training computation, using the previous frame ID to find the real previous frame image and target information as cancat features, will the effect be better?

We didn't verify when their amounts of training computation are the same.
