### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinnal

### ISSUE THREAD

**Issue by tehseenmayar** [PeizeSun/TransTrack#24]
Hi,
Thanks for your great work.
I am trying to reproduce your results and i have been following the steps your describe but after executing `sh track_exps/crowdhuman_train.sh` i got the error: "RuntimeError: CUDA error: invalid device ordinnal", I think it's because of the number of gpus default id, can you tell me how to change it to train on 1 gpu? or maybe guide me if i am missing something. I am using google colab.
Thanks

**Comment by PeizeSun** [comment]
Hi~
To train on 1 gpu, just change the number of nproc_per_node to 1 in 
`python3 -m torch.distributed.launch --nproc_per_node=8 --use_env main_track.py  --output_dir ./output_crowdhuman --dataset_file crowdhuman --coco_path crowdhuman --batch_size 2  --with_box_refine --num_queries 500 --epochs 150 --lr_drop 100
`
or direct run 
`python3 main_track.py  --output_dir ./output_crowdhuman --dataset_file crowdhuman --coco_path crowdhuman --batch_size 2  --with_box_refine --num_queries 500 --epochs 150 --lr_drop 100
`
