### ISSUE TITLE
Errors when testing on customer video which has a long sequences without people appearing

### ISSUE THREAD

**Issue by Xingyu-Jin** [PeizeSun/TransTrack#25]
Hi, when I run mot_test.sh on my own video, it gives error
```
Test:  [ 6120/17958]  eta: 0:36:03  class_error: 100.00  loss: 0.0854 (3.0055)  loss_ce: 0.0187 (0.1138)  loss_bbox: 0.0000 (0.0711)  loss_giou: 0.0000 (0.3172)  loss_ce_0: 0.0126 (0.0945)  loss_bbox_0: 0.0000 (0.0723)  loss_giou_0: 0.0000 (0.3325)  loss_ce_1: 0.0167 (0.1124)  loss_bbox_1: 0.0000 (0.0727)  loss_giou_1: 0.0000 (0.3258)  loss_ce_2: 0.0161 (0.1037)  loss_bbox_2: 0.0000 (0.0725)  loss_giou_2: 0.0000 (0.3240)  loss_ce_3: 0.0132 (0.0974)  loss_bbox_3: 0.0000 (0.0718)  loss_giou_3: 0.0000 (0.3220)  loss_ce_4: 0.0093 (0.1024)  loss_bbox_4: 0.0000 (0.0729)  loss_giou_4: 0.0000 (0.3265)  loss_ce_unscaled: 0.0093 (0.0569)  class_error_unscaled: 100.0000 (27.9203)  loss_bbox_unscaled: 0.0000 (0.0142)  loss_giou_unscaled: 0.0000 (0.1586)  cardinality_error_unscaled: 500.0000 (498.9012)  loss_ce_0_unscaled: 0.0063 (0.0473)  loss_bbox_0_unscaled: 0.0000 (0.0145)  loss_giou_0_unscaled: 0.0000 (0.1662)  cardinality_error_0_unscaled: 500.0000 (498.9012)  loss_ce_1_unscaled: 0.0084 (0.0562)  loss_bbox_1_unscaled: 0.0000 (0.0145)  loss_giou_1_unscaled: 0.0000 (0.1629)  cardinality_error_1_unscaled: 500.0000 (498.9012)  loss_ce_2_unscaled: 0.0081 (0.0518)  loss_bbox_2_unscaled: 0.0000 (0.0145)  loss_giou_2_unscaled: 0.0000 (0.1620)  cardinality_error_2_unscaled: 500.0000 (498.9012)  loss_ce_3_unscaled: 0.0066 (0.0487)  loss_bbox_3_unscaled: 0.0000 (0.0144)  loss_giou_3_unscaled: 0.0000 (0.1610)  cardinality_error_3_unscaled: 500.0000 (498.9012)  loss_ce_4_unscaled: 0.0046 (0.0512)  loss_bbox_4_unscaled: 0.0000 (0.0146)  loss_giou_4_unscaled: 0.0000 (0.1632)  cardinality_error_4_unscaled: 500.0000 (498.9012)  time: 0.1651  data: 0.0022  max mem: 870
Traceback (most recent call last):
  File "main_track.py", line 367, in <module>
    main(args)
  File "main_track.py", line 289, in main
    test_stats, coco_evaluator, res_tracks = evaluate(model, criterion, postprocessors, data_loader_val,
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/projects/TransTrack/engine_track.py", line 152, in evaluate
    res_track = tracker.step(results[0])
  File "/projects/TransTrack/models/tracker.py", line 110, in step
    track['tracking_id'] = tracks[m1]['tracking_id']
KeyError: 'tracking_id'

```
I went back the 6120th frame and found there was a long sequence with no people for from 5000th frame. This might be somehow related to the error? do you have idea why there is no key of tracking_id here?

**Comment by Xingyu-Jin** [comment]
just for your convinience, say if there is no tracks in history, refering to 
`
        tracks = [v for v in self.tracks_dict.values()] + self.unmatched_tracks        N = len(results)        M = len(tracks)                ret = list()        unmatched_tracks = [d for d in range(M)]        if N &gt; 0 and M &gt; 0:            det_box   = torch.stack([torch.tensor(obj['bbox']) for obj in results], dim=0) # N x 4                    track_box = torch.stack([torch.tensor(obj['bbox']) for obj in tracks], dim=0) # M x 4                            cost_bbox = 1.0 - box_ops.generalized_box_iou(det_box, track_box) # N x M
            matched_indices = linear_sum_assignment(cost_bbox)            unmatched_dets = [d for d in range(N) if not (d in matched_indices[0])]            unmatched_tracks = [d for d in range(M) if not (d in matched_indices[1])]
            matches = [[],[]]            for (m0, m1) in zip(matched_indices[0], matched_indices[1]):                if cost_bbox[m0, m1] &gt; 1.2:                    unmatched_dets.append(m0)                    unmatched_tracks.append(m1)                else:                    matches[0].append(m0)                    matches[1].append(m1)
            for (m0, m1) in zip(matches[0], matches[1]):                track = results[m0]                track['tracking_id'] = tracks[m1]['tracking_id']                track['age'] = 1                track['active'] = 1                pre_box = tracks[m1]['bbox']                cur_box = track['bbox']`

**Comment by PeizeSun** [comment]
Hi~ 
Thank you for reporting this bug. We just refine the code of tracker.py. Can you test on your customer dataset to see whether it works?

**Comment by Xingyu-Jin** [comment]
@PeizeSun Hey, thank you sm. Just back from holidays. I'm on it now and will have to wait for around a day to get the run done due to the size of my dataset. will keep u posted

**Comment by Xingyu-Jin** [comment]
the issue is solved without any errors now but I got some odd results if you would like to take a look.
![Screenshot from 2021-06-02 22-44-46](https://user-images.githubusercontent.com/17474067/120556280-31362280-c3f4-11eb-8d8c-2ec6fb696973.png)
the IL_OFFICE_1 and IL_OFFICE_2 datasets have 0 idf1 and negative numbers for MOTA.
The town centre has a negtive numbers for MOTA as well.

**Comment by PeizeSun** [comment]
I guess it is related to the way of computing idf1, but I am not very clear.

**Comment by Xingyu-Jin** [comment]
Hi I visualized the frame and found the cause. so in the video, each frame there are around 2 false positive tracks on models in shopping windows. results are both correct. This may lead to some potential of improvement that if the net could understand the models in shopping windows should not be tracked with some tricks like larger context or smth. Just for your insight and would be happy to discuss.

**Comment by PeizeSun** [comment]
Maybe NMS is a simple and effective method to reduce the duplicated boxes in shopping windows(but NMS is against end-to-end design philosophy of Transformer-based detector.)
