### ISSUE TITLE
About reported higher performance score

### ISSUE THREAD

**Issue by yunseung-dable** [PeizeSun/TransTrack#27]
hi 😁

Appreciate your great work!

in README.md, you stated higher performance reported when using mixed dataset.

so I want to know what score is that exactly.

**Comment by PeizeSun** [comment]
Hi~
Please refer to README.md
![image](https://user-images.githubusercontent.com/40374966/124732086-72ff3f00-df45-11eb-9154-ecb3c31428d5.png)

**Comment by yunseung-dable** [comment]
so, you mean MOTA 74.5 written on your paper is the best score?
but you described on your paper(table.1) TransTrack achieved MOTA 74.5 with only crowdhuman dataset.

**Comment by PeizeSun** [comment]
> so, you mean MOTA 74.5 written on your paper is the best score?
> but you described on your paper(table.1) TransTrack achieved MOTA 74.5 with only crowdhuman dataset.

The data column in Table 1 is external data besides mot.
