### ISSUE TITLE
Test MOT17 test set, performance 54.1?

### ISSUE THREAD

**Issue by yuzhiyiliu** [PeizeSun/TransTrack#28]
$ python3 main_track.py  --output_dir . --dataset_file mot --coco_path mot --batch_size 1 --resume model/619mot17_mot17.pth --eval --with_box_refine --num_queries 500

Test: Total time: 1:00:17 (1.3641 s / it)
Accumulating evaluation results...
DONE (t=2.52s).
IoU metric: bbox
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = **0.541**
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.884
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.589
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.080
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.440
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.636

 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.050
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.345
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.641
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.223
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.573
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.719
Creating video index for mot.

**Comment by PeizeSun** [comment]
Hi~
54.1 is AP metric, mot17 usually uses MOTA as metric.
Please run `sh track_exps/mota.sh` to get MOTA.

**Comment by yuzhiyiliu** [comment]
Thanks for your quick reply,
![TransTrack_MOT17_test](https://user-images.githubusercontent.com/20537090/124899041-4e24cd80-e012-11eb-8a93-8096d4f2e084.png)
But I got MOTA 61.9%, am I set up incorrectly?

**Comment by PeizeSun** [comment]
MOTA 61.9% is exactly correct. This is performance on validation set.
If you want to test on test set, please refer to [MOT challenge](https://motchallenge.net/).

**Comment by yuzhiyiliu** [comment]
Thx~,
Are there any samples in your repo?

**Comment by yuzhiyiliu** [comment]
$ python3 main_track.py --output_dir . --dataset_file mot --coco_path mot --batch_size 1 --resume model/619mot17_mot17.pth --track_eval_split test --eval --with_box_refine  --num_queries 500

Test: Total time: 6:32:09 (1.3251 s / it)
Averaged stats: **class_error: 100.00**  loss: 154.3566 (431.0294)  loss_ce: 33.7268 (98.5663)  loss_bbox: 0.0000 (0.0000)  loss_giou: 0.0000 (0.0000)  loss_ce_0: 20.7482 (60.7730)  loss_bbox_0: 0.0000 (0.0000)  loss_giou_0: 0.0000 (0.0000)  loss_ce_1: 25.3040 (65.3062)  loss_bbox_1: 0.0000 (0.0000)  loss_giou_1: 0.0000 (0.0000)  loss_ce_2: 26.7121 (67.1159)  loss_bbox_2: 0.0000 (0.0000)  loss_giou_2: 0.0000 (0.0000)  loss_ce_3: 24.3467 (70.0842)  loss_bbox_3: 0.0000 (0.0000)  loss_giou_3: 0.0000 (0.0000)  loss_ce_4: 22.4293 (69.1838)  loss_bbox_4: 0.0000 (0.0000)  loss_giou_4: 0.0000 (0.0000)  loss_ce_unscaled: 16.8634 (49.2832)  class_error_unscaled: 100.0000 (100.0000)  loss_bbox_unscaled: 0.0000 (0.0000)  loss_giou_unscaled: 0.0000 (0.0000)  cardinality_error_unscaled: 500.0000 (500.0000)  loss_ce_0_unscaled: 10.3741 (30.3865)  loss_bbox_0_unscaled: 0.0000 (0.0000)  loss_giou_0_unscaled: 0.0000 (0.0000)  cardinality_error_0_unscaled: 500.0000 (499.9284)  loss_ce_1_unscaled: 12.6520 (32.6531)  loss_bbox_1_unscaled: 0.0000 (0.0000)  loss_giou_1_unscaled: 0.0000 (0.0000)  cardinality_error_1_unscaled: 500.0000 (499.9495)  loss_ce_2_unscaled: 13.3561 (33.5580)  loss_bbox_2_unscaled: 0.0000 (0.0000)  loss_giou_2_unscaled: 0.0000 (0.0000)  cardinality_error_2_unscaled: 500.0000 (499.9973)  loss_ce_3_unscaled: 12.1733 (35.0421)  loss_bbox_3_unscaled: 0.0000 (0.0000)  loss_giou_3_unscaled: 0.0000 (0.0000)  cardinality_error_3_unscaled: 500.0000 (499.9633)  loss_ce_4_unscaled: 11.2147 (34.5919)  loss_bbox_4_unscaled: 0.0000 (0.0000)  loss_giou_4_unscaled: 0.0000 (0.0000)  cardinality_error_4_unscaled: 500.0000 (499.9916)
Accumulating evaluation results...
DONE (t=6.79s).
IoU metric: bbox
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = **-1.000**
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
Creating video index for mot.


Hi @PeizeSun 
I got AP -1.00, am I set up incorrectly?

**Comment by PeizeSun** [comment]
Please ignore this AP -1 is because no annotation is provided for test set. If you need the result on test set, please submit to [MOT challenge](https://motchallenge.net/).
