### ISSUE TITLE
performance of TransTrack training with extra five datasets

### ISSUE THREAD

**Issue by MasterBin-IIAU** [PeizeSun/TransTrack#29]
Hi, thanks for the great work. I have a question about the training datasets.
As shown in the Table. 1 of the TransTrack paper, TransTrack achieves great performance compared with many SOTA methods trained with much more extra datasets (5D1 or 5D2). I am wondering that what if also training TransTrack with these extra datasets, could the performance be stronger?

**Comment by iFighting** [comment]
> Hi, thanks for the great work. I have a question about the training datasets.
> As shown in the Table. 1 of the TransTrack paper, TransTrack achieves great performance compared with many SOTA methods trained with much more extra datasets (5D1 or 5D2). I am wondering that what if also training TransTrack with these extra datasets, could the performance be stronger?

sure，the performance will be stronger with more extra datasets.
Since i see that your research interest is object tracking through your homepage, we can discuss this topic with each other
