### ISSUE TITLE
why num_classes=20 and questions about multiple decoders?

### ISSUE THREAD

**Issue by jrcai** [PeizeSun/TransTrack#30]
Hi, thanks for the great work. I was wondering why num_classes is 20 in this work, not 2?
besides, do the number of decoders (Appendix B) mean the number of decoder branches or just decoder layers?

Many thanks in advance!

**Comment by PeizeSun** [comment]
Hi~
We find that if num_classes is 1, the training may be unstable.
Appendix B means decoder layers.

**Comment by jrcai** [comment]
Hi Peize, thank you for replying. Do you mean num_classes>1 should work, not necessary that num_classes = 20?

**Comment by PeizeSun** [comment]
Yes, but we didn't verified yet.
