### ISSUE TITLE
Re-ID features code release?

### ISSUE THREAD

**Issue by Jiachengyou** [PeizeSun/TransTrack#31]
Thanks for so nice work！I saw your experiment for Re-ID features model in section 4.5.2, but I can't find the code in this repository. Do you release the code for this part?

**Comment by PeizeSun** [comment]
Hi~
We are improving the re-ID features code recently. We will update it as soon as possible.

**Comment by Jiachengyou** [comment]
Thanks for your reply. Waiting for it ！

**Comment by PeizeSun** [comment]
Hi~
We have release re-ID feature [code](https://github.com/PeizeSun/TransTrack/tree/main/models/reid).
