### ISSUE TITLE
Many ID switches between the frame 0 and frame 1

### ISSUE THREAD

**Issue by rvrsprdx** [PeizeSun/TransTrack#36]
Hi,

thanks for your great work.
I've tried it on a custom dataset and it works great overall.
However, between frame 0 and frame 1 of every test sequence (and also train sequence) there are many id switches.
In fact, >66% of all detections of frame 0 get a different id on frame 1.
After frame 1 the tracking works pretty well.

Have you encountered such an issue before?
Or do you maybe have an idea?

Thanks!

**Comment by PeizeSun** [comment]
Hi~
We didn't encounter such an issue before.
Do you change the code(except for dataset)?

**Comment by rvrsprdx** [comment]
Thanks for you response.
I did not change the code. Only the things concering the dataset...

**Comment by rvrsprdx** [comment]
The issue was on my side. Everything's ok now.
