### ISSUE TITLE
Running on video

### ISSUE THREAD

**Issue by rvrsprdx** [PeizeSun/TransTrack#38]
Hi,

I have a video I want to run TransTrack on to visually see how it perfoms. (Don't need any quantitative evaluation)
It's a simple video without any annotations.
How could this be achieved?

Thx!

**Comment by PeizeSun** [comment]
Hi~
We just add  demo.py  code, you can use it by 
`python3 demo.py --video_input video.mp4 --demo_output demo_output --resume checkpoint671.pth --with_box_refine`
