### ISSUE TITLE
Use pre-trained model

### ISSUE THREAD

**Issue by DioMou** [PeizeSun/TransTrack#39]
Hello, I am not sure how to use the pretrained model, including where to save it and how the pretrained model is read and used. Also, in order to visualize the result, do I have to train by myself?
If anybody can help me with this issue, it would be grateful. Thank you very much.

**Comment by JackWoo0831** [comment]
Hello DioMou, I hope I can help you.
Do you mean how to run a demo using the pre-trained model?

Firstly, you should download the pre-trained model and prepare a demo video. Then you should rename the video as 'demo.mp4' and put it in the root dir.
Secondly, If you open demo.py, you can see that in line 178:
`   _, _ = model.load_state_dict(checkpoint['model'], strict=False)`

and then you can find the arg in line115:
**    parser.add_argument('--resume', default='', help='resume from checkpoint')`**

so you should run as:(for example, the checkpoint file I downloaded is 619mot17_mot17.pth)
`python demo.py --resume=models/619mot17_mot17.pth`
