### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by BrainPotter** [PeizeSun/TransTrack#51]
Hi, thank you for your great work.
My OS is ubuntu16.04, which has 4 NVIDIA Geforce RTX 2080, 
When I run the program sh track_exps/crowdhuman_mot_trainhalf.sh,
it gave the error CUDA out of memory.
the crowdhuman_mot_trainhalf.sh is set as:
python3 -m torch.distributed.launch --nproc_per_node=4 --use_env main_track.py  --output_dir ./output/crowdhuman_mot_trainhalf --dataset_file mot --coco_path mot --batch_size 2  --with_box_refine  --num_queries 500 --resume crowdhuman_final.pth --epochs 200 --lr_drop 10
and I use the MOT17 as the training set (which is 6.1GB).
Are there any changes of parameters or something except --batchsize 2 and --dataset_file mot? I have tried some times about this training progress and always got the same error. 

I'd appreciate your help.
Thanks!

**Comment by PeizeSun** [comment]
Hi~
If the batch size can't be reduced, maybe you could try to reduce the image size.
