### ISSUE TITLE
 Unexpected compiler version, expected CUDA 10.1 Update 2 or newer.

### ISSUE THREAD

**Issue by shiguangliuguo** [PeizeSun/TransTrack#52]
thanks for your work!
but when i run "python setup.py build install"
![U4MTDZ%$%P$BA)HY83AQ724](https://user-images.githubusercontent.com/49485196/145166313-609a20e7-9386-41a2-b1bf-b83376137ab9.png)
happened, i dont know what i should do.

**Comment by PeizeSun** [comment]
Hi~
It seems you are installing on Windows OS. Unluckily, our code doesn't support Windows OS.

**Comment by shiguangliuguo** [comment]
yes，now i change my os to Ubuntu, it's ok!
