### ISSUE TITLE
ImportError:cannot import name '_NewEmptyTensorOp' from 'torchvision.ops.misc'

### ISSUE THREAD

**Issue by 2713286758** [PeizeSun/TransTrack#53]
I run demo.py to test model that provided by  author, but get an error.
So i find a problem in "util/misc.py", in line 21 and line 48.
I think the code "version.parse(torchvision.__version__)" only consider version from 0.1.0 to 0.9.9, but didn't consider latest version e.g. 0.10.0.

I'd appreciate for your answer.
Thanks!

**Comment by PeizeSun** [comment]
Hi~
Thanks for reporting this bug. We have fixed it. Can you re-try the code ?

**Comment by 2713286758** [comment]
I replace the file and run code again. It runs successfully.
Thanks for your work.
