### ISSUE TITLE
which detector of MOT17?

### ISSUE THREAD

**Issue by shiguangliuguo** [PeizeSun/TransTrack#54]
hi,thanks for your nice work!
that's my first time to train MOT17, I don't know how to use MOT17, choose which detector to train?
Looking for your response.

**Comment by shiguangliuguo** [comment]
should i delete other detector dataset in MOT17?
then run convert_mot_to_coco.py?
thanks!

**Comment by PeizeSun** [comment]
Hi~
Please follow the provided steps in README.
