### ISSUE TITLE
about training logs

### ISSUE THREAD

**Issue by haak0** [PeizeSun/TransTrack#6]
hi, peize, could you provide the training log?
I don't have 8 v100 devices for training , so I need to reduce the batch size.
your training log surely helps me check the training process.

Best.

**Comment by PeizeSun** [comment]
Hi~ Could you tell me your e-mail? and I will send the training log to you.

**Comment by haak0** [comment]
Thanks, please send it to my qq mailbox  (1009532436@qq.com).

**Comment by tehseenmayar** [comment]
Hi, Can you send the log files to me too? 
Here is my email: tehseen@phystech.edu
I would appreciate that

**Comment by PeizeSun** [comment]
> Hi, Can you send the log files to me too?
> Here is my email: [tehseen@phystech.edu](mailto:tehseen@phystech.edu)
> I would appreciate that

The e-mail has been cc to you.

**Comment by jer1ry** [comment]
Hello, Can you send the log files to me too?
Here is my email:907866043@qq.com
I will look forward to your reply
