### ISSUE TITLE
Different argument of MSAttention compared to DeformableDETR

### ISSUE THREAD

**Issue by IlchaeJung** [PeizeSun/TransTrack#61]
Thanks for your fantastic research. 
Recently, I studied your transtrack implementation and have an one question.
In my observation, there is an one ignored argument, "value_level_start_index" from MSAttentionFunction of Deformable DETR.
And, the detailed changes are implemented in cuda codes. 

I want to know that this change makes functional differences between the two implementations (msatten@Deformabledetr v.s. msttn@transtrack)? 
Please react me if you confirm this issue.

**Comment by PeizeSun** [comment]
Hi~
This is because our implementation uses an older version of DeformableDETR, which may not be public in the DeformableDETR repo.

**Comment by IlchaeJung** [comment]
thank you!
