### ISSUE TITLE
KeyError: 'frame_id'

### ISSUE THREAD

**Issue by AngusMrli** [PeizeSun/TransTrack#63]
Hi,
I encountered a problem in trying to pre train, that is, the steps of using training commands:
`sh track_exps/crowdhuman_train.sh`
When I use a single GPU or multiple GPUs, the following errors occur:
`Traceback (most recent call last):
  File "main_track.py", line 390, in <module>
    main(args)
  File "main_track.py", line 195, in main
    sampler_val = DistributedVideoSampler(dataset_val, start_id=args.start_id, shuffle=False)
  File "/root/autodl-tmp/TransTrack/datasets/sampler_video_distributed.py", line 36, in __init__
    if img_info['frame_id'] == start_id:
KeyError: 'frame_id'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2488) of binary: /root/miniconda3/bin/python3`
There is no problem in the above steps. I don't know the cause of the problem.Thank you.

**Comment by PeizeSun** [comment]
Hi~
Thanks for reporting this bug. We have fixed it just now.
