### ISSUE TITLE
A problem about position embedding

### ISSUE THREAD

**Issue by AngusMrli** [PeizeSun/TransTrack#64]
Hi,
In the process of reading the code, I wonder whether transtrack really needs to use `position embedding`. Where are position embedding used in your work? Whether position embedding is not used at the encoder end, but only at the decoder end. In addition, is it unnecessary to use `mask` in the field of image processing?
Thank you.

**Comment by PeizeSun** [comment]
Hi~
1. The position embedding is used in the encoder, [lvl_pos_embed_flatten](https://github.com/PeizeSun/TransTrack/blob/main/models/deformable_transformer_track.py#L156).
2. In our implementation, the position embedding is not used in the decoder. We set query_pos as NONE,  [query_embed](https://github.com/PeizeSun/TransTrack/blob/main/models/deformable_transformer_track.py#L172).
3. Mask is used to set the padding area as zero. [mask](https://github.com/PeizeSun/TransTrack/blob/7c3458a85a981b7c9a935c264133b477928f4648/models/ops/modules/ms_deform_attn.py#L65)
