### ISSUE TITLE
 RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by colinqin7686** [PeizeSun/TransTrack#7]
what is the exactly version of torch and torchvision.I have tried torch 1.7 with python 3.8 and torch 1.5 with python 3.6, both of which are failed. So could you tell me  the exactly version of torch and torchvision so as to continue.

**Comment by PeizeSun** [comment]
Hi, here is our platform environment:

sys.platform            linux
Python                  3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
numpy                   1.18.1
Compiler                GCC 8.3
CUDA compiler           CUDA 10.2
PyTorch                 1.5.0 
GPU available           True
GPU 0,1,2,3,4,5,6,7     Tesla V100-SXM2-32GB (arch=7.0)
torchvision             0.6.0a0+82fd1c8 
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
cv2                     4.4.0

**Comment by flyinskybtx** [comment]
This helped me out:

changing devtoolset-8/root/usr/include/c++/8/bits/basic_string.tcc:1067 from this:

__p->_M_set_sharable();

to this seems to fix the compiler error:

(*__p)._M_set_sharable();

--ref: https://forums.developer.nvidia.com/t/cuda-10-1-nvidia-youre-now-fixing-gcc-bugs-that-gcc-doesnt-even-have/71063/10
