### ISSUE TITLE
Test on new videos

### ISSUE THREAD

**Issue by akshu281** [PeizeSun/TransTrack#8]
Dear Author,

Thank you for your great work, however this is all trained and evaluated on MOT dataset. Say, if I have to use this model trained on a new video to track pedestrians how do I go about like how DeepSORT can be used with other object detectors to run in any new video ?

Thank You for your help !

**Comment by PeizeSun** [comment]
Hi~ 
TransTrack is a joint-detection-and-tracking pipeline, instead of an independent tracker. So, the right way to apply TransTrack is training it on your own videos.

**Comment by khadijakhaldi** [comment]
Hi,
can we use TransTrack with our own detections? 
Thanks!
